services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: movie-stack-backend
    ports:
      - "5002:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - TMDB_API_KEY=${TMDB_API_KEY:-}
      - TMDB_BASE_URL=https://api.themoviedb.org/3
      - TMDB_IMAGE_BASE_URL=https://image.tmdb.org/t/p
      - OMDB_API_KEY=${OMDB_API_KEY:-}
      - OMDB_BASE_URL=${OMDB_BASE_URL:-http://www.omdbapi.com}
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://127.0.0.1:5000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: movie-stack-frontend
    ports:
      - "3002:80"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: movie-stack-network
